on: [push]
name: build
jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
      - name: Build
        env:
          CC: clang
          CXX: clang++
        run: |
          cmake -B build
          cmake --build build
      - name: Test
        run: ./integration-test.sh
  build-linux-gcc:
    runs-on: ubuntu-latest
    name: Linux GCC
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -B build
          cmake --build build
      - name: Test
        run: ./integration-test.sh
  build-macos:
    runs-on: macOS-latest
    name: macOS
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          CC: clang
          CXX: clang++
        run: |
          cmake -B build
          cmake --build build
      - name: Test
        run: ./integration-test.sh
