on: [push]
name: build
jobs:
  build-nix:
    runs-on: ubuntu-latest
    name: Nix
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build
  build-linux:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"
      - name: Build
        env:
          CC: clang
          CXX: clang++
        run: |
          cmake -B build
          cmake --build build
      - name: Test
        run: ./integration-test.sh
  build-macos:
    runs-on: macOS-latest
    name: macOS
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          CC: clang
          CXX: clang++
        run: |
          cmake -B build
          cmake --build build
      - name: Test
        run: ./integration-test.sh
